server:
  port: 8089

spring:
  jpa:
    database: postgresql
    hibernate:
      dialect: org.hibernate.dialect.PostgresSQLDialect
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    show-sql: true

  datasource:
    hikari:
      maximum-pool-size: 4
    url: jdbc:postgresql://ec2-44-215-211-215.compute-1.amazonaws.com/d3v9fre9buc2di
    username: awdpwbdgnqhtjj
    password: 67b461993f43be193e6025f8b6e3601cc6e089e522136c4da2a793b912149e5c
    platform: postgres
    driver-class-name: org.postgresql.Driver


jwt:
  secret-key:
    jung.sns-application-2023.secret_key

  # 39 days (ms단위로 계산)
  token.expired-time-ms: 2592000000